# Generated by Django 5.1.4 on 2025-03-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_kyc_image_holding_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='investment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Investment'),
        ),
    ]
